#!/bin/sh

dir=`pwd`

installedIndex=0
notInstalledIndex=0;
removedIndex=0;

function install(){
    which brew || ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
    [[ -z ~/.oh-my-zsh ]] && curl -L http://install.ohmyz.sh | sh
    for file in .*; do
	      if [[ -e "$HOME/$file" ]]; then
	          if [[ ! -L "$HOME/$file" ]]; then
		            if [[ ".emacs.d" == $file ]]; then
                    echo "- $HOME/$file has contents. Copy whatever files you want and then delete the directory before attempting to install again"
		            fi
            else
                notInstalled[$notInstalledIndex]="$file"
                let "notInstalledIndex += 1"
            fi
        elif [[ $file == ".git" ]]; then
            :
        elif [[ $file == ".gitignore" ]]; then
            :
        else
            ln -s $dir/$file $HOME/$file
            installed[$installedIndex]="$file"
            if [[ $file == ".lesskey" ]]; then
                `which lesskey` && `lesskey .lesskey`
            elif [[ $file == ".mac_keybindings" ]]; then 
		keybinding_dir="$HOME/Library/KeyBindings"
                if [[ ! -e $keybinding_dir ]]; then
		    mkdir -p $keybinding_dir
		    ln -s $dir/.mac_keybindings $keybinding_dir/DefaultKeyBinding.dict
		fi
            fi
            let "installedIndex += 1"
	      fi
    done

    echo "RESULTS:"
    if [[ $installedIndex > 0 ]]; then
        for (( j=0; j < $installedIndex; j++ )); do
            results=$results"${installed[$j]}"
            if [[ $j+1 -ne $installedIndex ]]; then
                results="$results, "
            fi
        done
        echo "$results were installed to $HOME."
    fi
    results=""
    if [[ $notInstalledIndex > 0 ]]; then
        for (( j=0; j < $notInstalledIndex; j++ )); do
            results=$results"${notInstalled[$j]}"
            if [[ $j+1 -ne $notInstalledIndex ]]; then
                results="$results, "
            fi
        done
        echo "$results already exist, so they were not installed."
    fi
}

function setDefaults() {
    defaults write NSGlobalDomain KeyRepeat -int 0
}

function uninstall(){
    for file in .*; do
	      if [[ $file != "." ]] && [[ $file != ".." ]]; then
            if [[ -L "$HOME/$file" ]]; then
                removed[$removedIndex]="$file"
                let "removedIndex += 1"
	              rm -rf $HOME/$file
            fi
	      fi
    done

    if [[ $removedIndex > 0 ]]; then
        for (( j=0; j < $removedIndex; j++ )); do
            echo -n ${removed[$j]}
            if [[ $j+1 -ne $removedIndex ]]; then echo -n ", "; fi
        done
        echo " were removed from $HOME"
    fi

}

function brew_install(){
    brew_list=`cat brew_list`
    brew_taps=`cat brew_taps`
    brew tap $brew_taps
    brew install $brew_list
}

function pip_install(){
    pip install `cat pip_freeze`
}
function npm_install(){
    npm install -g `cat npm_list`
}

function updateLists(){
    brew tap > brew_taps
    brew list > brew_list
    pip freeze > pip_freeze
    ls `npm root -g` > npm_list
}

if [[ -z $1 ]]; then
    echo "No command given"
elif [[ $1 == "-u" || $1 == "--update" ]]; then
    updateLists
else
    for arg in $@; do
        if [[ $arg == "-i" || $arg == "--install" ]]; then
            install
            setDefaults
        #elif [[ $arg == "-u" || $arg == "--uninstall" ]]; then
        #    uninstall
        elif [[ $arg == "-b" || $arg == "--brew" ]]; then
            brew_install
        elif [[ $arg == "-p" || $arg == "--pip" ]]; then
            pip_install
        elif [[ $arg == "-n" || $arg == "--npm" ]]; then
            npm_install
        else
            echo "Incorrect command given: $arg"
        fi
    done
fi
