#!/bin/bash

dir=`pwd`

installedIndex=0
notInstalledIndex=0;
removedIndex=0;

function install(){
    for file in .*; do
	      if [[ -e "$HOME/$file" ]]; then
	          if [[ ! -L "$HOME/$file" ]]; then
		            if [[ ".emacs.d" == $file ]]; then
                    echo "- $HOME/$file has contents. Copy whatever files you want and then delete the directory before attempting to install again"
		            fi
            else
                notInstalled[$notInstalledIndex]="$file"
                let "notInstalledIndex += 1"
            fi
	      elif [[ $file == ".git" ]]; then
	          echo -n #do nothing
        else
            ln -s $dir/$file $HOME/$file
            installed[$installedIndex]="$file"
            let "installedIndex += 1"
	      fi
    done

    echo "RESULTS:"
    if [[ $installedIndex > 0 ]]; then
        for (( j=0; j < $installedIndex; j++ )); do
            echo -n ${installed[$j]}
            if [[ $j+1 -ne $installedIndex ]]; then echo -n ", "; fi
        done
        echo " were installed to $HOME"
    fi
    if [[ $notInstalledIndex > 0 ]]; then
        for (( j=0; j < $notInstalledIndex; j++ )); do
            echo -n ${notInstalled[$j]}
            if [[ $j+1 -ne $notInstalledIndex ]]; then echo -n ", "; fi
        done
        echo " already exist, so they were not installed"
    fi
}

function uninstall(){
    for file in .*; do
	      if [[ $file != "." ]] && [[ $file != ".." ]]; then
            if [[ -L "$HOME/$file" ]]; then
                removed[$removedIndex]="$file"
                let "removedIndex += 1"
	              rm -rf $HOME/$file
            fi
	      fi
    done

    if [[ $removedIndex > 0 ]]; then
        for (( j=0; j < $removedIndex; j++ )); do
            echo -n ${removed[$j]}
            if [[ $j+1 -ne $removedIndex ]]; then echo -n ", "; fi
        done
        echo " were removed from $HOME"
    fi

}

if [[ $1 == "-i" || $1 == "--install" ]]; then
    install
elif [[ $1 == "-u" || $1 == "--uninstall" ]]; then
    uninstall
elif [[ -z $1 ]]; then
    echo "No command given"
else
    echo "Incorrect command given"
fi
