#!/bin/sh

dir=`pwd`

installedIndex=0
notInstalledIndex=0;
removedIndex=0;

function install(){
    for file in .*; do
	      if [[ -e "$HOME/$file" ]]; then
	          if [[ ! -L "$HOME/$file" ]]; then
		            if [[ ".emacs.d" == $file ]]; then
                    echo "- $HOME/$file has contents. Copy whatever files you want and then delete the directory before attempting to install again"
		            fi
            else
                notInstalled[$notInstalledIndex]="$file"
                let "notInstalledIndex += 1"
            fi
	      elif [[ $file == ".git" ]]; then
	          echo -n #do nothing
        else
            ln -s $dir/$file $HOME/$file
            installed[$installedIndex]="$file"
            let "installedIndex += 1"
	      fi
    done

    echo "RESULTS:"
    if [[ $installedIndex > 0 ]]; then
        for (( j=0; j < $installedIndex; j++ )); do
            echo -n ${installed[$j]}
            if [[ $j+1 -ne $installedIndex ]]; then echo -n ", "; fi
        done
        echo " were installed to $HOME"
    fi
    if [[ $notInstalledIndex > 0 ]]; then
        for (( j=0; j < $notInstalledIndex; j++ )); do
            echo -n ${notInstalled[$j]}
            if [[ $j+1 -ne $notInstalledIndex ]]; then echo -n ", "; fi
        done
        echo " already exist, so they were not installed"
    fi
}

function uninstall(){
    for file in .*; do
	      if [[ $file != "." ]] && [[ $file != ".." ]]; then
            if [[ -L "$HOME/$file" ]]; then
                removed[$removedIndex]="$file"
                let "removedIndex += 1"
	              rm -rf $HOME/$file
            fi
	      fi
    done

    if [[ $removedIndex > 0 ]]; then
        for (( j=0; j < $removedIndex; j++ )); do
            echo -n ${removed[$j]}
            if [[ $j+1 -ne $removedIndex ]]; then echo -n ", "; fi
        done
        echo " were removed from $HOME"
    fi

}

function brew_install(){
    brew_list=`cat brew_list`
    echo "brew install "$brew_list
}

function pip_install(){
    echo "pip install "`cat pip_freeze`
}

if [[ -z $1 ]]; then
    echo "No command given"
else
    for arg in $@; do
        if [[ $arg == "-i" || $arg == "--install" ]]; then
            echo "install" #install
        #elif [[ $arg == "-u" || $arg == "--uninstall" ]]; then
        #    uninstall
        elif [[ $arg == "-b" || $arg == "--brew" ]]; then
            brew_install
        elif [[ $arg == "-p" || $arg == "--pip" ]]; then
            pip_install
        else
            echo "Incorrect command given: $arg"
        fi
    done
fi



